// Start Category Types
export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const CREATE_CATEGORY = "CREATE_CATEGORY"
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY"
// Start Sub category Types
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY"
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY"
export const GET_ERROR = "GET_ERROR"
// Start Brand Types
export const GET_ALL_BRAND = "GET_ALL_BRAND"
export const CREATE_BRAND = "CREATE_BRAND"
export const GET_ONE_BRAND = "GET_ONE_BRAND"
// Start Products Types
export const CREATE_PRODUCT = "CREATE_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_ONE_PRODUCTS = "GET_ONE_PRODUCTS";
export const GET_SIMILER_PRODUCTS = "GET_SIMILER_PRODUCTS";
export const GET_ALL_TYPES = "GET_ALL_TYPES";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const GET_ALL_PRODUCTS_CATEGORY = "GET_ALL_PRODUCTS_CATEGORY";
export const GET_ALL_PRODUCTS_BRAND = "GET_ALL_PRODUCTS_BRAND";
// Start Authentication Types
export const CREATE_ACCOUNT = "CREATE_ACCOUNT"
export const LOGIN = "LOGIN";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"
// Start REVIEW Types
export const CREATE_REVIEW = "CREATE_REVIEW"
export const VIEW_REVIEW = "VIEW_REVIEW"
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW"
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
// Start Address Types
export const ADD_ADDRESS = "ADD_ADDRESS"
export const GET_ADDRESS = "GET_ADDRESS"
export const DELETE_ADDRESS ="DELETE_ADDRESS"
export const EDIT_ADDRESS = "EDIT_ADDRESS";
export const GET_SPETIFIC_ADDRESS = "GET_SPETIFIC_ADDRESS"
// Start Wishlist Types
export const USER_WISHLIST = "USER_WISHLIST"
export const ADD_PRODUCT_WISHLIST = "ADD_PRODUCT_WISHLIST"
export const REMOVE_PRODUCT_WISHLIST = "REMOVE_PRODUCT_WISHLIST"
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE"
// Start Coupon Types
export const CREATE_COUPON = "CREATE_COUPON"
export const GET_ALL_COUPON = "GET_ALL_COUPON"
export const DELETE_COUPON = "DELETE_COUPON"
export const UPDATE_COUPON = "UPDATE_COUPON"
export const GET_ONE_COUPON = "GET_ONE_COUPON"
// Start Cart Types
export const ADD_CART = "ADD_CART";
export const ALL_CART = "ALL_CART";
export const REMOVE_ONE_CART = "REMOVE_ONE_CART";
export const REMOVE_ALL_CART = "REMOVE_ALL_CART";
export const APPLY_COUPON_CART = "APPLY_COUPON_CART";
export const QUANTITY_CART = "QUANTITY_CART";
// Order Types
export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const UPDATE_ORDER_DELIVER = "UPDATE_ORDER_DELIVER";
export const UPDATE_ORDER_PAY ="UPDATE_ORDER_PAY"
export const GET_ONE_ORDER = "GET_ONE_ORDER"
export const CREATE_ORDER_CASH ="CREATE_ORDER_CASH"





